extend type Assignment {
  """
  ✨ List `UserAssignment` objects in a one-to-many relationship (where `UserAssignment`.`assignment` is this object).
  """
  userAssignments_on_assignment(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAssignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAssignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAssignment_Having
  ): [UserAssignment!]! @fdc_generated(from: "UserAssignment.assignment", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `UserAssignment` as the join table (a `UserAssignment` object exists where its `assignment` is this and its `user` is that).
  """
  users_via_UserAssignment(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAssignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAssignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAssignment_Having
  ): [User!]! @fdc_generated(from: "UserAssignment", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Assignment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Assignment` table.
  """
  _count: Int! @fdc_generated(from: "Assignment.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Assignment` table where the `courseName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  courseName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Assignment.courseName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Assignment` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Assignment.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Assignment` table where the `externalId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  externalId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Assignment.externalId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Assignment` table where the `source` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  source_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Assignment.source", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Assignment` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Assignment.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Assignment` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Assignment.url", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `dueDate` field in the `Assignment` table.
  """
  dueDate_min: Timestamp @fdc_generated(from: "Assignment.dueDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `dueDate` field in the `Assignment` table.
  """
  dueDate_max: Timestamp @fdc_generated(from: "Assignment.dueDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Assignment.externalId", purpose: ENTITY_ID)
}
extend type Course {
  """
  ✨ List `Assignment` objects in a one-to-many relationship (where `Assignment`.`course` is this object).
  """
  assignments_on_course(
    """
    Filter condition to narrow down the query results.
    """
    where: Assignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Assignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Assignment_Having
  ): [Assignment!]! @fdc_generated(from: "Assignment.course", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Enrollment` objects in a one-to-many relationship (where `Enrollment`.`course` is this object).
  """
  enrollments_on_course(
    """
    Filter condition to narrow down the query results.
    """
    where: Enrollment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Enrollment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Enrollment_Having
  ): [Enrollment!]! @fdc_generated(from: "Enrollment.course", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `Enrollment` as the join table (a `Enrollment` object exists where its `course` is this and its `user` is that).
  """
  users_via_Enrollment(
    """
    Filter condition to narrow down the query results.
    """
    where: Enrollment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Enrollment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Enrollment_Having
  ): [User!]! @fdc_generated(from: "Enrollment", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Course", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Course` table.
  """
  _count: Int! @fdc_generated(from: "Course.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Course` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Course.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Course.name", purpose: ENTITY_ID)
}
extend type Enrollment {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Enrollment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Enrollment` table.
  """
  _count: Int! @fdc_generated(from: "Enrollment.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Enrollment` table where the `courseName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  courseName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Enrollment.courseName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Enrollment` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Enrollment.userUid", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Enrollment.userUid,courseName", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Enrollment` objects in a one-to-many relationship (where `Enrollment`.`user` is this object).
  """
  enrollments_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Enrollment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Enrollment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Enrollment_Having
  ): [Enrollment!]! @fdc_generated(from: "Enrollment.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserAssignment` objects in a one-to-many relationship (where `UserAssignment`.`user` is this object).
  """
  userAssignments_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAssignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAssignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAssignment_Having
  ): [UserAssignment!]! @fdc_generated(from: "UserAssignment.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Assignment` objects using `UserAssignment` as the join table (a `UserAssignment` object exists where its `user` is this and its `assignment` is that).
  """
  assignments_via_UserAssignment(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAssignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAssignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAssignment_Having
  ): [Assignment!]! @fdc_generated(from: "UserAssignment", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  ✨ List `Course` objects using `Enrollment` as the join table (a `Enrollment` object exists where its `user` is this and its `course` is that).
  """
  courses_via_Enrollment(
    """
    Filter condition to narrow down the query results.
    """
    where: Enrollment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Enrollment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Enrollment_Having
  ): [Course!]! @fdc_generated(from: "Enrollment", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `courseConfigs` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  courseConfigs_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.courseConfigs", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `uid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  uid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.uid", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.uid", purpose: ENTITY_ID)
}
extend type UserAssignment {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserAssignment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserAssignment` table.
  """
  _count: Int! @fdc_generated(from: "UserAssignment.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAssignment` table where the `assignmentExternalId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  assignmentExternalId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAssignment.assignmentExternalId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAssignment` table where the `score` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  score_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAssignment.score", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAssignment` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAssignment.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAssignment` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAssignment.userUid", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserAssignment.userUid,assignmentExternalId", purpose: ENTITY_ID)
}
